# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openllm.v1 import service_pb2 as openllm_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in openllm/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class McpBridgeStub(object):
    """
    MCP Bridge Service - High-performance tool execution

    This service provides gRPC transport for MCP tools, combining:
    - MCP's semantic layer (tool definitions, JSON schemas for LLM understanding)
    - gRPC's performance layer (HTTP/2 multiplexing, bidirectional streaming)

    The "hybrid bridge" pattern: Keep the brain (MCP schemas), upgrade the pipe (gRPC).


    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMcpTools = channel.unary_unary(
                '/openllm.v1.McpBridge/ListMcpTools',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListMcpToolsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListMcpToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_stream(
                '/openllm.v1.McpBridge/CallTool',
                request_serializer=openllm_dot_v1_dot_service__pb2.CallToolRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ToolResponseChunk.FromString,
                _registered_method=True)
        self.CallToolInteractive = channel.stream_stream(
                '/openllm.v1.McpBridge/CallToolInteractive',
                request_serializer=openllm_dot_v1_dot_service__pb2.ToolInteractiveRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ToolResponseChunk.FromString,
                _registered_method=True)
        self.CallToolsBatch = channel.unary_stream(
                '/openllm.v1.McpBridge/CallToolsBatch',
                request_serializer=openllm_dot_v1_dot_service__pb2.CallToolsBatchRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ToolResponseChunk.FromString,
                _registered_method=True)
        self.ListResources = channel.unary_unary(
                '/openllm.v1.McpBridge/ListResources',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListResourcesRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListResourcesResponse.FromString,
                _registered_method=True)
        self.ReadResource = channel.unary_unary(
                '/openllm.v1.McpBridge/ReadResource',
                request_serializer=openllm_dot_v1_dot_service__pb2.ReadResourceRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ReadResourceResponse.FromString,
                _registered_method=True)
        self.ListPrompts = channel.unary_unary(
                '/openllm.v1.McpBridge/ListPrompts',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListPromptsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListPromptsResponse.FromString,
                _registered_method=True)
        self.GetPrompt = channel.unary_unary(
                '/openllm.v1.McpBridge/GetPrompt',
                request_serializer=openllm_dot_v1_dot_service__pb2.GetPromptRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.GetPromptResponse.FromString,
                _registered_method=True)


class McpBridgeServicer(object):
    """
    MCP Bridge Service - High-performance tool execution

    This service provides gRPC transport for MCP tools, combining:
    - MCP's semantic layer (tool definitions, JSON schemas for LLM understanding)
    - gRPC's performance layer (HTTP/2 multiplexing, bidirectional streaming)

    The "hybrid bridge" pattern: Keep the brain (MCP schemas), upgrade the pipe (gRPC).


    """

    def ListMcpTools(self, request, context):
        """Discovery: List available MCP tools with their schemas
        Returns full MCP tool definitions so LLMs understand what's available
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Execution: Call a tool with streaming response
        Supports progress updates, partial results, and cancellation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallToolInteractive(self, request_iterator, context):
        """Bidirectional: For tools that need user input mid-execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallToolsBatch(self, request, context):
        """Batch: Execute multiple independent tools in parallel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResources(self, request, context):
        """Resources: List MCP resources (files, data sources)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadResource(self, request, context):
        """Resources: Read a specific resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrompts(self, request, context):
        """Prompts: List available MCP prompts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrompt(self, request, context):
        """Prompts: Get a prompt with arguments filled in
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMcpTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMcpTools,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListMcpToolsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListMcpToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_stream_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.CallToolRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ToolResponseChunk.SerializeToString,
            ),
            'CallToolInteractive': grpc.stream_stream_rpc_method_handler(
                    servicer.CallToolInteractive,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ToolInteractiveRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ToolResponseChunk.SerializeToString,
            ),
            'CallToolsBatch': grpc.unary_stream_rpc_method_handler(
                    servicer.CallToolsBatch,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.CallToolsBatchRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ToolResponseChunk.SerializeToString,
            ),
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListResourcesRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListResourcesResponse.SerializeToString,
            ),
            'ReadResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadResource,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ReadResourceRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ReadResourceResponse.SerializeToString,
            ),
            'ListPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrompts,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListPromptsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListPromptsResponse.SerializeToString,
            ),
            'GetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrompt,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.GetPromptRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.GetPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openllm.v1.McpBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openllm.v1.McpBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class McpBridge(object):
    """
    MCP Bridge Service - High-performance tool execution

    This service provides gRPC transport for MCP tools, combining:
    - MCP's semantic layer (tool definitions, JSON schemas for LLM understanding)
    - gRPC's performance layer (HTTP/2 multiplexing, bidirectional streaming)

    The "hybrid bridge" pattern: Keep the brain (MCP schemas), upgrade the pipe (gRPC).


    """

    @staticmethod
    def ListMcpTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.McpBridge/ListMcpTools',
            openllm_dot_v1_dot_service__pb2.ListMcpToolsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListMcpToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openllm.v1.McpBridge/CallTool',
            openllm_dot_v1_dot_service__pb2.CallToolRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ToolResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallToolInteractive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/openllm.v1.McpBridge/CallToolInteractive',
            openllm_dot_v1_dot_service__pb2.ToolInteractiveRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ToolResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallToolsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openllm.v1.McpBridge/CallToolsBatch',
            openllm_dot_v1_dot_service__pb2.CallToolsBatchRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ToolResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.McpBridge/ListResources',
            openllm_dot_v1_dot_service__pb2.ListResourcesRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.McpBridge/ReadResource',
            openllm_dot_v1_dot_service__pb2.ReadResourceRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ReadResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.McpBridge/ListPrompts',
            openllm_dot_v1_dot_service__pb2.ListPromptsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListPromptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.McpBridge/GetPrompt',
            openllm_dot_v1_dot_service__pb2.GetPromptRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.GetPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OpenLLMStub(object):
    """
    Main Service - Unified daemon API



    Chat

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/openllm.v1.OpenLLM/Chat',
                request_serializer=openllm_dot_v1_dot_service__pb2.ChatRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.SessionChat = channel.unary_stream(
                '/openllm.v1.OpenLLM/SessionChat',
                request_serializer=openllm_dot_v1_dot_service__pb2.SessionChatRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/openllm.v1.OpenLLM/CreateSession',
                request_serializer=openllm_dot_v1_dot_service__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/openllm.v1.OpenLLM/GetSession',
                request_serializer=openllm_dot_v1_dot_service__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Session.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/openllm.v1.OpenLLM/ListSessions',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/openllm.v1.OpenLLM/DeleteSession',
                request_serializer=openllm_dot_v1_dot_service__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.WatchSessions = channel.unary_stream(
                '/openllm.v1.OpenLLM/WatchSessions',
                request_serializer=openllm_dot_v1_dot_service__pb2.WatchSessionsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.SessionEvent.FromString,
                _registered_method=True)
        self.ReplaySession = channel.unary_unary(
                '/openllm.v1.OpenLLM/ReplaySession',
                request_serializer=openllm_dot_v1_dot_service__pb2.ReplaySessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ReplaySessionResponse.FromString,
                _registered_method=True)
        self.SummarizeSession = channel.unary_unary(
                '/openllm.v1.OpenLLM/SummarizeSession',
                request_serializer=openllm_dot_v1_dot_service__pb2.SummarizeSessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.SummarizeSessionResponse.FromString,
                _registered_method=True)
        self.ForkSession = channel.unary_unary(
                '/openllm.v1.OpenLLM/ForkSession',
                request_serializer=openllm_dot_v1_dot_service__pb2.ForkSessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Session.FromString,
                _registered_method=True)
        self.ExportSession = channel.unary_unary(
                '/openllm.v1.OpenLLM/ExportSession',
                request_serializer=openllm_dot_v1_dot_service__pb2.ExportSessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ExportSessionResponse.FromString,
                _registered_method=True)
        self.ImportSession = channel.unary_unary(
                '/openllm.v1.OpenLLM/ImportSession',
                request_serializer=openllm_dot_v1_dot_service__pb2.ImportSessionRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Session.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/openllm.v1.OpenLLM/ListModels',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.DiscoverModels = channel.unary_unary(
                '/openllm.v1.OpenLLM/DiscoverModels',
                request_serializer=openllm_dot_v1_dot_service__pb2.DiscoverModelsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.DiscoverModelsResponse.FromString,
                _registered_method=True)
        self.ListProviders = channel.unary_unary(
                '/openllm.v1.OpenLLM/ListProviders',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.GetProviderStatus = channel.unary_unary(
                '/openllm.v1.OpenLLM/GetProviderStatus',
                request_serializer=openllm_dot_v1_dot_service__pb2.GetProviderStatusRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ProviderStatus.FromString,
                _registered_method=True)
        self.ListEngines = channel.unary_unary(
                '/openllm.v1.OpenLLM/ListEngines',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListEnginesRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListEnginesResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/openllm.v1.OpenLLM/ListPolicies',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/openllm.v1.OpenLLM/ListTools',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/openllm.v1.OpenLLM/ExecuteTool',
                request_serializer=openllm_dot_v1_dot_service__pb2.ExecuteToolRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ExecuteToolResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/openllm.v1.OpenLLM/GetConfig',
                request_serializer=openllm_dot_v1_dot_service__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Config.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/openllm.v1.OpenLLM/UpdateConfig',
                request_serializer=openllm_dot_v1_dot_service__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Config.FromString,
                _registered_method=True)
        self.GetSecret = channel.unary_unary(
                '/openllm.v1.OpenLLM/GetSecret',
                request_serializer=openllm_dot_v1_dot_service__pb2.GetSecretRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.GetSecretResponse.FromString,
                _registered_method=True)
        self.SetSecret = channel.unary_unary(
                '/openllm.v1.OpenLLM/SetSecret',
                request_serializer=openllm_dot_v1_dot_service__pb2.SetSecretRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteSecret = channel.unary_unary(
                '/openllm.v1.OpenLLM/DeleteSecret',
                request_serializer=openllm_dot_v1_dot_service__pb2.DeleteSecretRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.ListSecrets = channel.unary_unary(
                '/openllm.v1.OpenLLM/ListSecrets',
                request_serializer=openllm_dot_v1_dot_service__pb2.ListSecretsRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.ListSecretsResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/openllm.v1.OpenLLM/Register',
                request_serializer=openllm_dot_v1_dot_service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/openllm.v1.OpenLLM/Unregister',
                request_serializer=openllm_dot_v1_dot_service__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/openllm.v1.OpenLLM/GetStatus',
                request_serializer=openllm_dot_v1_dot_service__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.DaemonStatus.FromString,
                _registered_method=True)
        self.GetConnectedWorkspaces = channel.unary_unary(
                '/openllm.v1.OpenLLM/GetConnectedWorkspaces',
                request_serializer=openllm_dot_v1_dot_service__pb2.GetConnectedWorkspacesRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.GetConnectedWorkspacesResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/openllm.v1.OpenLLM/Shutdown',
                request_serializer=openllm_dot_v1_dot_service__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/openllm.v1.OpenLLM/HealthCheck',
                request_serializer=openllm_dot_v1_dot_service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.StartWebServer = channel.unary_unary(
                '/openllm.v1.OpenLLM/StartWebServer',
                request_serializer=openllm_dot_v1_dot_service__pb2.StartWebServerRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.StartWebServerResponse.FromString,
                _registered_method=True)
        self.StopWebServer = channel.unary_unary(
                '/openllm.v1.OpenLLM/StopWebServer',
                request_serializer=openllm_dot_v1_dot_service__pb2.StopWebServerRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.RegisterMcpServer = channel.unary_unary(
                '/openllm.v1.OpenLLM/RegisterMcpServer',
                request_serializer=openllm_dot_v1_dot_service__pb2.RegisterMcpServerRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.UnregisterMcpServer = channel.unary_unary(
                '/openllm.v1.OpenLLM/UnregisterMcpServer',
                request_serializer=openllm_dot_v1_dot_service__pb2.UnregisterMcpServerRequest.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.Empty.FromString,
                _registered_method=True)
        self.VSCodeStream = channel.stream_stream(
                '/openllm.v1.OpenLLM/VSCodeStream',
                request_serializer=openllm_dot_v1_dot_service__pb2.VSCodeResponse.SerializeToString,
                response_deserializer=openllm_dot_v1_dot_service__pb2.VSCodeRequest.FromString,
                _registered_method=True)


class OpenLLMServicer(object):
    """
    Main Service - Unified daemon API



    Chat

    """

    def Chat(self, request, context):
        """Stateless chat (no session persistence)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionChat(self, request, context):
        """Chat within a session (persisted)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """
        Sessions


        Create a new session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Get a session by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List all sessions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Delete a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSessions(self, request, context):
        """Watch for session events (create, update, delete)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaySession(self, request, context):
        """Replay session for context injection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeSession(self, request, context):
        """Get AI-generated summary of a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkSession(self, request, context):
        """Fork a session (create new session from existing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportSession(self, request, context):
        """Export session as portable JSON
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportSession(self, request, context):
        """Import a session from JSON
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """
        Models & Providers


        List available models (config-gated: only configured/enabled models)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverModels(self, request, context):
        """Discover all models a provider offers (ignores config, for browsing/selection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviders(self, request, context):
        """List configured providers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderStatus(self, request, context):
        """Get provider status (configured, healthy, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEngines(self, request, context):
        """List available engine types (fixed set of API implementations)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """
        Policies


        List all policies (built-in + custom)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """
        Tools


        List available tools (from MCP servers)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Execute a tool directly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """
        Configuration


        Get current configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Update configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecret(self, request, context):
        """
        Secrets


        Get a secret (API key, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSecret(self, request, context):
        """Set a secret
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """Delete a secret
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecrets(self, request, context):
        """List secret keys (not values)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """
        Daemon Lifecycle


        Register a client connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister a client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get daemon status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedWorkspaces(self, request, context):
        """Get workspaces from connected VS Code clients (queries via backchannel)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Request daemon shutdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWebServer(self, request, context):
        """
        Web Dashboard (embedded in daemon)


        Start the embedded web server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopWebServer(self, request, context):
        """Stop the embedded web server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterMcpServer(self, request, context):
        """
        MCP Server Registration (for external MCP servers)


        Register an MCP server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterMcpServer(self, request, context):
        """Unregister an MCP server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VSCodeStream(self, request_iterator, context):
        """
        VS Code Backchannel (Bidirectional Streaming)

        VS Code opens this stream and keeps it alive.
        The daemon pushes tool/model requests through it.
        VS Code sends responses back through the same stream.


        Bidirectional stream for daemon to call VS Code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenLLMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ChatRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ChatChunk.SerializeToString,
            ),
            'SessionChat': grpc.unary_stream_rpc_method_handler(
                    servicer.SessionChat,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.SessionChatRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ChatChunk.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.CreateSessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.GetSessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Session.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListSessionsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListSessionsResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.DeleteSessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'WatchSessions': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSessions,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.WatchSessionsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.SessionEvent.SerializeToString,
            ),
            'ReplaySession': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaySession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ReplaySessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ReplaySessionResponse.SerializeToString,
            ),
            'SummarizeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeSession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.SummarizeSessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.SummarizeSessionResponse.SerializeToString,
            ),
            'ForkSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkSession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ForkSessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Session.SerializeToString,
            ),
            'ExportSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportSession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ExportSessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ExportSessionResponse.SerializeToString,
            ),
            'ImportSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportSession,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ImportSessionRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Session.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListModelsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListModelsResponse.SerializeToString,
            ),
            'DiscoverModels': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverModels,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.DiscoverModelsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.DiscoverModelsResponse.SerializeToString,
            ),
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListProvidersRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListProvidersResponse.SerializeToString,
            ),
            'GetProviderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderStatus,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.GetProviderStatusRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ProviderStatus.SerializeToString,
            ),
            'ListEngines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEngines,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListEnginesRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListEnginesResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListPoliciesRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListToolsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListToolsResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ExecuteToolRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ExecuteToolResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.GetConfigRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Config.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.UpdateConfigRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Config.SerializeToString,
            ),
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.GetSecretRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.GetSecretResponse.SerializeToString,
            ),
            'SetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSecret,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.SetSecretRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'DeleteSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecret,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.DeleteSecretRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'ListSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecrets,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ListSecretsRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.ListSecretsResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.RegisterRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.RegisterResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.UnregisterRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.GetStatusRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.DaemonStatus.SerializeToString,
            ),
            'GetConnectedWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedWorkspaces,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.GetConnectedWorkspacesRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.GetConnectedWorkspacesResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.ShutdownRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.HealthCheckRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'StartWebServer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWebServer,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.StartWebServerRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.StartWebServerResponse.SerializeToString,
            ),
            'StopWebServer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopWebServer,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.StopWebServerRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'RegisterMcpServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMcpServer,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.RegisterMcpServerRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'UnregisterMcpServer': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterMcpServer,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.UnregisterMcpServerRequest.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.Empty.SerializeToString,
            ),
            'VSCodeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.VSCodeStream,
                    request_deserializer=openllm_dot_v1_dot_service__pb2.VSCodeResponse.FromString,
                    response_serializer=openllm_dot_v1_dot_service__pb2.VSCodeRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openllm.v1.OpenLLM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openllm.v1.OpenLLM', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenLLM(object):
    """
    Main Service - Unified daemon API



    Chat

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openllm.v1.OpenLLM/Chat',
            openllm_dot_v1_dot_service__pb2.ChatRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openllm.v1.OpenLLM/SessionChat',
            openllm_dot_v1_dot_service__pb2.SessionChatRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/CreateSession',
            openllm_dot_v1_dot_service__pb2.CreateSessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/GetSession',
            openllm_dot_v1_dot_service__pb2.GetSessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ListSessions',
            openllm_dot_v1_dot_service__pb2.ListSessionsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/DeleteSession',
            openllm_dot_v1_dot_service__pb2.DeleteSessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openllm.v1.OpenLLM/WatchSessions',
            openllm_dot_v1_dot_service__pb2.WatchSessionsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.SessionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ReplaySession',
            openllm_dot_v1_dot_service__pb2.ReplaySessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ReplaySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/SummarizeSession',
            openllm_dot_v1_dot_service__pb2.SummarizeSessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.SummarizeSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ForkSession',
            openllm_dot_v1_dot_service__pb2.ForkSessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ExportSession',
            openllm_dot_v1_dot_service__pb2.ExportSessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ExportSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ImportSession',
            openllm_dot_v1_dot_service__pb2.ImportSessionRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ListModels',
            openllm_dot_v1_dot_service__pb2.ListModelsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/DiscoverModels',
            openllm_dot_v1_dot_service__pb2.DiscoverModelsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.DiscoverModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ListProviders',
            openllm_dot_v1_dot_service__pb2.ListProvidersRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/GetProviderStatus',
            openllm_dot_v1_dot_service__pb2.GetProviderStatusRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ProviderStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEngines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ListEngines',
            openllm_dot_v1_dot_service__pb2.ListEnginesRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListEnginesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ListPolicies',
            openllm_dot_v1_dot_service__pb2.ListPoliciesRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ListTools',
            openllm_dot_v1_dot_service__pb2.ListToolsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ExecuteTool',
            openllm_dot_v1_dot_service__pb2.ExecuteToolRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/GetConfig',
            openllm_dot_v1_dot_service__pb2.GetConfigRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Config.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/UpdateConfig',
            openllm_dot_v1_dot_service__pb2.UpdateConfigRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Config.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/GetSecret',
            openllm_dot_v1_dot_service__pb2.GetSecretRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.GetSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/SetSecret',
            openllm_dot_v1_dot_service__pb2.SetSecretRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/DeleteSecret',
            openllm_dot_v1_dot_service__pb2.DeleteSecretRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/ListSecrets',
            openllm_dot_v1_dot_service__pb2.ListSecretsRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.ListSecretsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/Register',
            openllm_dot_v1_dot_service__pb2.RegisterRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/Unregister',
            openllm_dot_v1_dot_service__pb2.UnregisterRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/GetStatus',
            openllm_dot_v1_dot_service__pb2.GetStatusRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.DaemonStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectedWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/GetConnectedWorkspaces',
            openllm_dot_v1_dot_service__pb2.GetConnectedWorkspacesRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.GetConnectedWorkspacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/Shutdown',
            openllm_dot_v1_dot_service__pb2.ShutdownRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/HealthCheck',
            openllm_dot_v1_dot_service__pb2.HealthCheckRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartWebServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/StartWebServer',
            openllm_dot_v1_dot_service__pb2.StartWebServerRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.StartWebServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopWebServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/StopWebServer',
            openllm_dot_v1_dot_service__pb2.StopWebServerRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterMcpServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/RegisterMcpServer',
            openllm_dot_v1_dot_service__pb2.RegisterMcpServerRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterMcpServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openllm.v1.OpenLLM/UnregisterMcpServer',
            openllm_dot_v1_dot_service__pb2.UnregisterMcpServerRequest.SerializeToString,
            openllm_dot_v1_dot_service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VSCodeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/openllm.v1.OpenLLM/VSCodeStream',
            openllm_dot_v1_dot_service__pb2.VSCodeResponse.SerializeToString,
            openllm_dot_v1_dot_service__pb2.VSCodeRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
